# Generated by Django 5.0.2 on 2024-02-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0007_remove_shoppingcart_products_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
