# Generated by Django 5.0.2 on 2024-02-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0011_remove_shoppingcart_user_shoppingcart_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='session',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
