# Generated by Django 5.0.2 on 2024-03-16 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='user_id',
            new_name='user',
        ),
    ]
